version: '3.3'

services:
  mysql_8_0_30:
    container_name: mysql_8_0_30
    build:
      context: ./
      args:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./mysql/mysql-data:/var/lib/mysql
    networks:
      - vuhso-microservices

networks:
  vuhso-microservices:
    external: true